# Generated by Django 4.2.2 on 2023-06-27 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='deal',
        ),
    ]
